// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsbaijtsrkvrnkjyioza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzYmFpanRzcmt2cm5ranlpb3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODY1NzcsImV4cCI6MjA2OTE2MjU3N30.YTo93m-XXSvPSUvKpdvFuxDXahol8S-ZJTxFrMwWwyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});